name: COMP9417_HW1

on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          conda env create --file environment.yml
          python comp9417_hw1_spec.py
          
          echo "######Testing#####" > report.md
          cat q1.out >> report.md
          cat q2.out >> report.md
          
          cml-send-comment report.md
